export const generateTypeDefinitions = (
  variables: Record<string, string>
): string => {
  const typeEntries = Object.keys(variables)
    .map((key) => `      ${key}: string | undefined;`)
    .join("\n");

  return `/**
 * Auto-generated file based on the .env file.
 * DO NOT EDIT THIS FILE MANUALLY.
 */

export {};

declare global {
  namespace NodeJS {
    interface ProcessEnv {
${typeEntries}
    }
  }
}`;
};
