/**
 * Auto-generated file based on the .env file.
 * DO NOT EDIT THIS FILE MANUALLY.
 */

export {};

declare global {
  namespace NodeJS {
    interface ProcessEnv {
      TURSO_DATABASE_URL: string;
      TURSO_AUTH_TOKEN: string;
      BETTER_AUTH_SECRET: string;
      ENABLE_OPEN_API: string;
    }
  }
}
