/**
 * Auto-generated file based on the .env file.
 * DO NOT EDIT THIS FILE MANUALLY.
 */

export {};

declare global {
  namespace NodeJS {
    interface ProcessEnv {
      TURSO_DATABASE_URL: string | undefined;
      TURSO_AUTH_TOKEN: string | undefined;
      BETTER_AUTH_SECRET: string | undefined;
      ENABLE_OPEN_API: string | undefined;
      ENABLE_SSL: string | undefined;
      APP_HOST: string | undefined;
      APP_PORT: string | undefined;
    }
  }
}
